# Copyright (c) 2023-2024 Westfall Inc.
#
# This file is part of Windbound.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, and can be found in the file NOTICE inside this
# git repository.
#
# This program is distributed in the hope that it will be useful
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[tool.poetry]
name = "windripper"
version = "0.0.18"
description = "Argo Sensor for Harbor Containers"
authors = ["Christopher Cox"]
license = "MIT"
readme = "README.md"
packages = [{ include = "main", from = "src" }]

[tool.semantic_release]
version_toml=[
    "pyproject.toml:tool.poetry.version",
    "pyproject.toml:project.version",
]
commit_parser = "emoji"
#build_command = "pip install poetry"
commit_message = ":bookmark:{version}\n\nAutomatically generated by python-semantic-release"

[tool.semantic_release.changelog]
exclude_commit_patterns = [":robot:",":twisted_rightwards_arrows:",
":poop:", "^[^:].*"]

[tool.semantic_release.commit_parser_options]
major_tags = [":boom:"]
minor_tags = [
    ":sparkles:",
    ":children_crossing:",
    ":lipstick:",
    ":iphone:",
    ":egg:",
    ":chart_with_upwards_trend:",
]
patch_tags = [
    ":ambulance:",
    ":lock:",
    ":bug:",
    ":zap:",
    ":goal_net:",
    ":alien:",
    ":wheelchair:",
    ":speech_balloon:",
    ":mag:",
    ":apple:",
    ":penguin:",
    ":checkered_flag:",
    ":robot:",
    ":green_apple:",
    ":memo:",
    ":heavy_plus_sign:",
    ":white_check_mark:",
]

#[tool.semantic_release.branches.main]
#match = "(main|master)"
#prerelease = false
#build_command = "pip install poetry && poetry build"

[project.urls]
"Homepage" = "https://github.com/Westfall-io/windripper"
"Bug Tracker" = "https://github.com/Westfall-io/windripper/issues"

[project]
name = "windripper"
version = "0.0.18"
authors = [
  { name="Christopher Cox", email="chris.cox@westfall.io" },
]
description = "Windripper"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
